name: moji_tracing
description: 4さい向け もじ なぞりがき れんしゅう アプリ
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path_drawing: ^1.0.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/strokes/hiragana.json
    - assets/strokes/katakana.json
    - assets/strokes/alphabet_upper.json
    - assets/strokes/alphabet_lower.json
